---
title: "Estatístico continua entre os profissionais mais procurados em 2019"
author: "por Willian Meira Schlichta"
date: "22 de fevereiro de 2019"
output: html_document
---


O segundo semestre de 2018 terminou com cerca de 13 milhões de desempregados no Brasil, segundo o Instituto Brasileiro de Geografia e Estatística (IBGE). No entanto, há uma grande procura por profissionais que saibam coletar, organizar e interpretar dados para sustentar a tomada de decisão em qualquer instituição. Esse é o resumo do que sabe fazer um Estatístico.

Na contramão da crise, bacharéis em Estatística possuem boas perspectivas em quesitos como renda e possibilidades de ascensão. Reportagem publicada no [Jornal Estado de Minas](https://www.em.com.br/app/noticia/especiais/educacao/2019/01/08/internas_educacao,1019826/confira-as-profissoes-que-prometem-ser-destaque-em-2019.shtml?fbclid=IwAR3p_gkkzDvq7IEbOGliO3DYdBfy683HDuL2GAN3p4MTNuO1JN8OleZeot4) aponta que das sete carreiras indicadas como promissoras, o estatístico pode ocupar cinco: Business Intelligence, Analista de SEO, Cientista de Dados, Diretor Financeiro e Analista de Mídias Digitais.

O mesmo é indicado na [Época Negócios](https://epocanegocios.globo.com/Carreira/noticia/2019/01/conheca-profissoes-que-estarao-em-alta-no-brasil-em-2019.html). Segundo as consultorias PageGroup e Robert Half, profissionais versáteis, bem relacionados e que acompanham as mudanças tecnológicas de forma integrada terão as melhores chances. Entre as carreiras que necessitam dos conhecimentos dos estatísticos estão o cientista de dados, o especialista em remuneração e profissionais que atuam na área de marketing.

“As oportunidades estão em todos os setores da economia: telecomunicações, saúde, mercado financeiro são alguns exemplos,” explica Julio Trecenti, Presidente do CONRE-3 (Conselho Regional de Estatística da Terceira Região, que engloba São Paulo, Paraná, Mato Grosso e Mato Grosso do Sul).

Nos Estados Unidos, as oportunidades de trabalho para profissionais de analytics saltaram para centenas de milhares, segundo websites de empregos como o [INDEED.COM](https://www.indeed.com.br/?r=us). Mesmo com o aumento substancial de formandos nos Estados Unidos, ainda há muito espaço para esse tipo de profissional.

O ranking anual do [CareerCast.com](httpshttps://www.careercast.com/jobs-rated/2018-best-jobs?page=4), site norte-americano especializado em empregos, colocou o Estatístico entre os cinco melhores da lista de melhores profissões nos Estados Unidos em 2018, com salário médio anual de US$ 84,060. Para eleger as melhores e piores profissões, o levantamento toma como base cinco critérios: demandas físicas, ambiente de trabalho, renda, estresse e perspectivas de contratação.

A carreira chegou a ser listada pelo Fórum Econômico Mundial como uma das mais relevantes para o mercado até 2020. Mas é preciso saber que além da facilidade com os números, também é preciso desenvolver habilidades de comunicação e conhecimentos em tecnologia.

“A estatística muda com o mundo e nós somos os líderes da ciência de dados. Precisamos nos posicionar se quisermos acompanhar as tendências. Além disso é preciso saber se expressar, para que os resultados das análises sejam compreensíveis por pessoas de outros departamentos”, explica Trecenti.

Conheça mais sobre a profissão visitando o site do Conre-3 [www.conre3.org.br](www.conre3.org.br).

Sobre a estatística – A Estatística segue entre as carreiras mais promissoras. Foi listada pelo Fórum Econômico Mundial como uma das mais relevantes para o mercado até 2020. Foi considerada a melhor carreira de 2017, segundo ranking anual do CareerCast.com, site norte-americano especializado em empregos, com salário médio anual de US$ 80,110. Em 2016, ficou em segundo lugar. No Brasil não é diferente. Segundo pesquisa do Instituto de Pesquisa Econômica Aplicada (Ipea), de 2013, entre 48 carreiras de nível superior, a estatística é a que apresenta a segunda melhor remuneração média no país, só perde para os médicos. Foi chamada de Profissão “Sexy” pela Revista Harvard Business Review e tem mais vagas de emprego do que profissionais formados. Foi regulamentada no Brasil pela Lei Federal Nº 4.739 de 1965.

Sobre o CONRE-3 – O Conselho Regional de Estatística da 3ª Região (CONRE-3), com sede no município de São Paulo, abrange os estados de São Paulo, Paraná, Mato Grosso e Mato Grosso do Sul. Foi constituído pelo Conselho Federal de Estatística (CONFE), em 1968. O órgão, entre suas atribuições, é responsável por zelar pelos interesses da profissão, além de fiscalizar e zelar pela ética profissional.

*********************